import assert from 'node:assert/strict'
import { access, readFile } from 'node:fs/promises'
import test from 'node:test'

test('Reference Client embeds the official Web UI in a Native Shell', async () => {
  const shell = await readFile(new URL('../assets/ReferenceShell.swift', import.meta.url), 'utf8')
  const runtime = await readFile(new URL('../assets/reference-client.mjs', import.meta.url), 'utf8')
  const rebase = await readFile(new URL('../assets/profile-rebase.mjs', import.meta.url), 'utf8')
  const updateState = await readFile(new URL('../assets/update-state.mjs', import.meta.url), 'utf8')
  const updater = await readFile(new URL('../assets/app-updater.mjs', import.meta.url), 'utf8')
  const info = await readFile(new URL('../assets/Info.plist', import.meta.url), 'utf8')

  assert.match(shell, /NSWindow/)
  assert.match(shell, /WKWebView/)
  assert.match(shell, /installApplicationMenu/)
  assert.match(shell, /Check for Updates/u)
  assert.match(shell, /Install Update/u)
  assert.match(shell, /app-updater\.mjs/u)
  assert.match(shell, /DSH_STACK_ACTIVE_APP/u)
  assert.match(shell, /DSH_STACK_APP_PID/u)
  assert.match(shell, /updateManifestURL/u)
  assert.match(shell, /Selector\(\("paste:"\)\)/u)
  assert.match(shell, /DSH_STACK_READY/)
  assert.match(shell, /environment\.removeValue\(forKey: name\)/u)
  assert.match(shell, /storageId/u)
  assert.doesNotMatch(shell, /Keychain|Security/u)
  assert.match(runtime, /DSH_STACK_READY/)
  assert.match(runtime, /--profile', profileName/u)
  assert.match(runtime, /storageId/u)
  assert.match(runtime, /DSH_STACK_APP_DATA/u)
  assert.match(runtime, /--health-check/u)
  assert.match(runtime, /delete runtimeEnvironment\[name\]/u)
  assert.match(runtime, /UPDATE_REBASE_CONFLICT/u)
  assert.match(runtime, /distribution-state\.json/u)
  assert.match(runtime, /acquireUpdateLock/u)
  assert.match(runtime, /acquireRuntimeLock/u)
  assert.match(runtime, /DISTRIBUTION_PROFILE_INVALID/u)
  assert.match(runtime, /assertUserStateUnchanged/u)
  assert.match(runtime, /recoverUpdateTransaction/u)
  assert.match(runtime, /commitApplicationUpdate/u)
  assert.match(rebase, /three-way rule/u)
  assert.match(rebase, /UPDATE_REBASE_CONFLICT/u)
  assert.doesNotMatch(runtime, /process\.env\[name\]/u)
  assert.doesNotMatch(runtime, /\bopen\s*\(/u)
  assert.match(updateState, /USER_STATE_CHANGED_DURING_UPDATE/u)
  assert.match(updateState, /writeAtomicJson/u)
  assert.match(updateState, /recoverUpdateTransaction/u)
  assert.match(updater, /installApplicationUpdate/u)
  assert.match(updater, /runHealthCheck/u)
  assert.match(updater, /APP_UPDATE_RECOVERY_FAILED/u)
  assert.match(updater, /verbatimSymlinks/u)
  assert.match(info, /<string>DeepSeek Desktop \(Unofficial\)<\/string>/u)
  assert.match(info, /<key>CFBundleIconFile<\/key>\s*<string>DeepSeekDesktop\.icns<\/string>/u)
  await access(new URL('../assets/DeepSeekDesktop.icns', import.meta.url))
})
